apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
spec:
  restartPolicy: Always
  containers:
  - name: mypod
    image: ubuntu
    imagePullPolicy: IfNotPresent
    env:
    - name: VAR
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: val
    command:
    - bash
    - -c
    #language=bash
    args:
    - |
      while true; do
        echo "$VAR"
        sleep 5
      done
  volumes:
  - name: myvolume
    configMap:
      name: myconfigmap
